### ISSUE TITLE
Ajouter de nouvelles commandes 

### ISSUE THREAD

**Issue by thomasdenecker** [IFB-ElixirFr/LinuxEBAII#14]
Il faudra en discuter pour le "où" mais je pense que nous devons ajouter dans ce cours :

- [x] rm 
- [x] rmdir
- [x] cp
- [x] mv

**Comment by paulineFrancoisAnses** [comment]
En complément de l'issue #5 
Note en + : A ajouter dans le cours 8 avec ls (-l -la -lha)

**Comment by paulineFrancoisAnses** [comment]
Ajouter aussi un point sur les droits, qu'ils comprennent pourquoi ils ne peuvent pas modifier certains dossiers (pas besoin d'aller trop loin dans les détails)

**Comment by paulineFrancoisAnses** [comment]
Tout a été ajouté au cours 8
