### ISSUE TITLE
Prototype d'une commande > Trouver de l’aide ! -> Problème formatage de l'aide (commande  ls 

### ISSUE THREAD

**Issue by dputhier** [IFB-ElixirFr/LinuxEBAII#17]
NNAAMMEE
                     ls - list directory contents

              SSYYNNOOPPSSIISS
                     llss [_O_P_T_I_O_N]... [_F_I_L_E]...

              DDEESSCCRRIIPPTTIIOONN
                     List  information  about  the FILEs (the current directory by default).
                     Sort entries alphabetically if none of --ccffttuuvvSSUUXX nor ----ssoorrtt  is  speci‐
                     fied.

**Comment by paulineFrancoisAnses** [comment]
Pas compris...

**Comment by paulineFrancoisAnses** [comment]
Ah si ok, ça devrait se résoudre en rejouant le book quand on le finalisera
